# Generated by Django 5.1.4 on 2024-12-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microservices_hotelpayment', '0002_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='client_id',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reservation_id',
            field=models.CharField(max_length=24),
        ),
    ]
