# Generated by Django 5.1.4 on 2024-12-12 14:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microservices_hotelpayment', '0003_alter_payment_client_id_alter_payment_reservation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=24, primary_key=True, serialize=False),
        ),
    ]
